# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rdrf.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdrf', '0092_auto_20181203_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=200)),
                ('elements_json', models.TextField(help_text="List of sections or cdes like: [{'type': 'section','code': 'xyz'}, {'type':'cde','code':'abc'}]")),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=rdrf.helpers.utils.generate_token, max_length=80, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('handler', models.CharField(default='WORKFLOW_REQUEST_HANDLER', max_length=80)),
                ('state', models.CharField(default='created', max_length=80)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reviewform',
            unique_together=set([('registry', 'code')]),
        ),
    ]
